### ISSUE TITLE
Create { _meta : { _index: 'myindex-MM-YYY' } } is ignored

### ISSUE THREAD

**Issue by nsainaney** [feathersjs-ecosystem/feathers-elasticsearch#58]
I have an index called `pagerduty` that has monthly aliases (`pagerduty-07-2018`,` pagerduty-08-2019` etc). The documentation states that `_meta` can have an `_index` property but this appears to be ignored.

```
const datedIndex = 'pagerduty-' + getMMYYYY(log_entry.created_at)
service.create({                            
  _id: incident.id,
  status: incident.status,
  title: incident.title,
  category: getCategory(incident.title),
  urgency: incident.urgency,
  timestamp: log_entry.created_at
   _meta: {_index: datedIndex }
})
```

**Comment by jciolek** [comment]
Hi @nsainaney,

Thanks for using feathers and feathers-elasticsearch!

With regards to the the `_meta` property the documentation states: "The meta field is an object containing elasticsearch specific information, e.g. _score, _type, _index, _parent, _routing and so forth. It will be stripped off from the documents passed to the service."

In other words, you can use the data coming from elasticsearceh in the `_meta` prop, however the service will promptly ignore everything you send to it in the `_meta` prop. This is intentional, and aimed to make updates easier. I hope that helps.

I'm closing this issue.

**Comment by nsainaney** [comment]
Understood - thanks
