### ISSUE TITLE
How to use whitelist

### ISSUE THREAD

**Issue by EliSadaka** [feathersjs-ecosystem/feathers-elasticsearch#77]
The latest update implemented whitelisting query parameters but the docs do not show how to use this option. I tried doing this but it didn't seem to work:

```
const postsElasticService = elasticService({
    Model: new elasticsearch.Client({
      host: process.env.ELASTICSEARCH_URL,
      apiVersion: '6.3',
    }),
    paginate: {
      default: 10,
      max: 50
    },
    elasticsearch: {
      index: 'posts',
      type: 'post'
    },
    whitelist: ['$phrase_prefix'],
    esVersion: '6.3'
  });
```

**Comment by jciolek** [comment]
Hey @EliSadaka,

Thanks for using Feathers and feathers-elasticsearch!

`$phrase_prefix` is whitelisted in the service by default:
https://github.com/feathersjs-ecosystem/feathers-elasticsearch/blob/master/lib/index.js#L29

The option you are passing should override the default whitelist, which would block other ES specific queries. Is that what is happening?

Thanks for pointing out the omission in the doc, good spot! I believed I missed it, because the whitelist is a standard Feathers service thing now (https://docs.feathersjs.com/api/databases/common.html#serviceoptions). I'll add it for completeness.

**Comment by EliSadaka** [comment]
Yes, I believe that's what was causing my issue. It works without overriding the whitelist.
